name: myip.blue Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: set NOW
        run: |
          echo "::set-env name=NOW::$(date +'%Y%m%d-%H%M')"
      - 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: 
            - ${{ secrets.DOCKER_HUB_USERNAME }}/myip.blue:latest
            - ${{ secrets.DOCKER_HUB_USERNAME }}/myip.blue:${{ env.NOW }}
